server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://192.168.64.200:3306/heima?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.64.200
    port: 6379
mybatis-plus:
  type-aliases-package: com.heima.item.pojo
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS
canal:
  destination: heima
  server: 192.168.64.200:11111